version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "app_extra_secret"
      MYSQL_USER: "app_user"
      MYSQL_PASSWORD: "app_extra_secret"
      MYSQL_DATABASE: "app"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
        - restify
  restify-demo:
    depends_on:
      - mysql
    build: .
    ports:
      - "3000:3000"
    container_name: restify-demo
    restart: unless-stopped
    environment:
      NODE_ENV: production
    networks:
      - restify
volumes:
  db_data: {}
networks:
  restify:
    driver: bridge